// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xdSnfxWCziyzb8tBiGitqa
// Component: 7aFEpfg1e-
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: F-KkpFIKCuog/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fantaasta.module.css"; // plasmic-import: xdSnfxWCziyzb8tBiGitqa/projectcss
import * as sty from "./PlasmicAstaItem.module.css"; // plasmic-import: 7aFEpfg1e-/css

export type PlasmicAstaItem__VariantMembers = {};

export type PlasmicAstaItem__VariantsArgs = {};
type VariantPropType = keyof PlasmicAstaItem__VariantsArgs;
export const PlasmicAstaItem__VariantProps = new Array<VariantPropType>();

export type PlasmicAstaItem__ArgsType = {
  astaname?: React.ReactNode;
  admin?: React.ReactNode;
  numpartecipants?: React.ReactNode;
};

type ArgPropType = keyof PlasmicAstaItem__ArgsType;
export const PlasmicAstaItem__ArgProps = new Array<ArgPropType>(
  "astaname",
  "admin",
  "numpartecipants"
);

export type PlasmicAstaItem__OverridesType = {
  root?: p.Flex<"div">;
  columns?: p.Flex<"div">;
};

export interface DefaultAstaItemProps {
  astaname?: React.ReactNode;
  admin?: React.ReactNode;
  numpartecipants?: React.ReactNode;
  className?: string;
}

function PlasmicAstaItem__RenderFunc(props: {
  variants: PlasmicAstaItem__VariantsArgs;
  args: PlasmicAstaItem__ArgsType;
  overrides: PlasmicAstaItem__OverridesType;
  dataFetches?: PlasmicAstaItem__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"columns"}
        data-plasmic-override={overrides.columns}
        className={classNames(defaultcss.all, sty.columns)}
      >
        <div className={classNames(defaultcss.all, sty.column__fuTIp)}>
          {p.renderPlasmicSlot({
            defaultContents: "Enter some text",
            value: args.astaname
          })}
        </div>

        <div className={classNames(defaultcss.all, sty.column__qYFxZ)}>
          {p.renderPlasmicSlot({
            defaultContents: "Enter some text",
            value: args.admin
          })}
        </div>

        <div className={classNames(defaultcss.all, sty.column__nrjb1)}>
          {p.renderPlasmicSlot({
            defaultContents: "Enter some text",
            value: args.numpartecipants
          })}
        </div>

        <div className={classNames(defaultcss.all, sty.column__rkeuo)} />

        <div className={classNames(defaultcss.all, sty.column__rqIbd)} />
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "columns"],
  columns: ["columns"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  columns: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAstaItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAstaItem__VariantsArgs;
    args?: PlasmicAstaItem__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicAstaItem__Fetches;
  } & Omit<PlasmicAstaItem__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAstaItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAstaItem__ArgProps,
      internalVariantPropNames: PlasmicAstaItem__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicAstaItem__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAstaItem";
  } else {
    func.displayName = `PlasmicAstaItem.${nodeName}`;
  }
  return func;
}

export const PlasmicAstaItem = Object.assign(
  // Top-level PlasmicAstaItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    columns: makeNodeComponent("columns"),

    // Metadata about props expected for PlasmicAstaItem
    internalVariantProps: PlasmicAstaItem__VariantProps,
    internalArgProps: PlasmicAstaItem__ArgProps
  }
);

export default PlasmicAstaItem;
/* prettier-ignore-end */
